apiVersion: v1
kind: Service
metadata:
  name: {{ include "wyoming-whisper.fullname" . }}
  labels:
    {{- include "wyoming-whisper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol |default "TCP" }}
      name: {{ .Values.service.name | default "http"}}
  selector:
    {{- include "wyoming-whisper.selectorLabels" . | nindent 4 }}
