apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
  SQLALCHEMY_DATABASE_URI: {{ tpl "{{ .Values.db.type }}://{{ .Values.db.username }}:{{ .Values.db.password }}@{{ .Values.db.host }}:{{.Values.db.port | toString }}/{{ .Values.db.database }}" . | b64enc | quote }}
