apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prom2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prom2mqtt.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.config_file.filename }}: |
    {{- .Values.config_file.data | toYaml | nindent 4 -}}
