{{- if .Values.ingressroute.enabled -}}
{{- $fullName := include "prom2mqtt.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
spec:
  entryPoints:
  {{- range .Values.ingressroute.entryPoints }}
    - {{ . }}
  {{- end }}
  routes:
    {{- range .Values.ingressroute.routes }}
    - match: Host(`{{ .url }}`)
      kind: Rule
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
          namespace: {{ .namespace }}
        {{- end }}
      services:
        - name: {{ $fullName }}
          kind: Service
          port: {{ $svcPort }}
    {{- end }}
{{- end }}